import { createServerClient } from "@supabase/ssr";
import { NextResponse, type NextRequest } from "next/server";

export async function proxy(request: NextRequest) {
  let supabaseResponse = NextResponse.next({
    request,
  });

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value }) => 
            request.cookies.set(name, value)
          );
          supabaseResponse = NextResponse.next({
            request,
          });
          cookiesToSet.forEach(({ name, value, options }) =>
            supabaseResponse.cookies.set(name, value, options)
          );
        },
      },
    }
  );

  // 1. Get the authenticated user
  const { data: { user } } = await supabase.auth.getUser();

  const pathname = request.nextUrl.pathname;

  // 2. Protect specific routes (e.g., everything inside /dashboard)
  // Ensure we don't block them if they are already heading to /pricing or /wallet
  if (user && pathname.startsWith("/dashboard") && !pathname.includes("/pricing")) {
    
    // 3. Fetch the subscription status using Supabase (Bypassing Prisma for the Edge)
    // Note: Ensure 'User' matches the exact table name generated by Prisma in your database
    const { data: dbUser } = await supabase
      .from('User')
      .select('isSubscribed, trialEndsAt, subscriptionPlan')
      .eq('id', user.id)
      .single();

    if (dbUser) {
      const now = new Date();
      const trialEndsAt = dbUser.trialEndsAt ? new Date(dbUser.trialEndsAt) : null;
      
      const isTrialExpired = trialEndsAt && trialEndsAt < now;
      const isPaidSub = dbUser.isSubscribed && dbUser.subscriptionPlan !== "TRIAL_7_DAY";

      // 4. THE BLOCKER: If trial is expired and they haven't paid, kick them to pricing
      if (isTrialExpired && !isPaidSub) {
        const url = request.nextUrl.clone();
        url.pathname = "/pricing"; // Assuming your subscription page is at /pricing
        url.searchParams.set("alert", "trial_expired");
        return NextResponse.redirect(url);
      }
    }
  }

  return supabaseResponse;
}

export const config = {
  matcher: [
    "/((?!_next/static|_next/image|favicon.ico|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)",
  ],
};